blank_issues_enabled: false
template: []
contact_links:
  - name: Leo Core Discussions
    url: https://github.com/Yesh48/LEOlabs/discussions
    about: Ask questions or share ideas with the community.
