apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "leo-core.fullname" . }}-config
  labels:
    {{- include "leo-core.labels" . | nindent 4 }}
data:
  WEIGHTS_YML: |-
{{- (.Files.Get "leo/config/weights.yml") | indent 4 }}
