{{- if and .Values.db.persistence.enabled .Values.db.postgres.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: leo-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: {{ .Values.db.persistence.storageClass | default "standard" }}
{{- end }}
