apiVersion: v1
kind: Secret
metadata:
  name: {{ include "leo-core.fullname" . }}-secrets
  labels:
    {{- include "leo-core.labels" . | nindent 4 }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.env.OPENAI_API_KEY | b64enc | quote }}
  LEO_DB_PASSWORD: {{ .Values.db.postgres.password | b64enc | quote }}
