apiVersion: v2
name: leo-core
description: Helm chart for Leo Core
version: 0.2.0
appVersion: 0.2.0
dependencies:
  - name: postgresql
    version: 12.10.0
    repository: https://charts.bitnami.com/bitnami
    condition: db.postgres.enabled
